local: &local
  project: campus-nyc-taxi
  jwt: your_key.json
  dataset: taxi_demand_local
  save_folder: .

development:
  <<: *local

production:
  project: campus-nyc-taxi
  jwt: your_key.json
  dataset: taxi_demand_prod
  save_folder: /home/airflow/gcs/data/taxi-demand-prediction

